version: '3.8'

services:

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: cart-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # Broker
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build: ./auth-service
    ports:
      - "3005:3005"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  cart-service:
    build: ./cart-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  inventory-service:
    build: ./inventory-service
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
    env_file:
      - .env

    depends_on:
      - rabbitmq

  shipping-service:
    build: ./shipping-service
    ports:
      - "3006:3006"
    env_file:
      - .env
    depends_on:
      - rabbitmq
