services:

  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # Broker
      - "15672:15672"    # Management UI
    env_file:
      - .env

  auth-service:
    build: ./auth-service
    ports:
      - "3005:3005"
    env_file:
      - ./auth-service/.env
    depends_on:
      - rabbitmq

  cart-service:
    build: ./cart-service
    ports:
      - "3001:3001"
    env_file:
      - ./cart-service/.env
    depends_on:
      - rabbitmq

  inventory-service:
    build: ./inventory-service
    ports:
      - "3003:3003"
    env_file:
      - ./inventory-service/.env
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    env_file:
      - ./order-service/.env
    depends_on:
      - rabbitmq

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
    env_file:
      - ./notification-service/.env

    depends_on:
      - rabbitmq

  shipping-service:
    build: ./shipping-service
    ports:
      - "3006:3006"
    env_file:
      - ./shipping-service/.env
    depends_on:
      - rabbitmq

volumes:
  pgdata:

